[package]
name = "great-appender"
version = "0.1.0"
authors = ["Tim Marinin <mt@humane.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="*"
signal-hook = "0.1.10"
bytefmt="*"